/**
 * @typedef {Array} phraseBank
 * @description This is where we store all of our phrases that we want to use for bingo tiles.
 */

const phraseBank = [
  'Dies says how old he is',
  "Dies asks 'what does that mean?' \r✨✨✨✨",
  //'10 people finish a challenge before the timer goes off ⏲️',
  'Dies mentions an OnlyFans page 🔞 ',
  // "Alissa posts a helpful link in chat 🔗",
  'Dies invites us to follow his Instagram',
  'Hydrate! 🚰',
  'Posture Check!',
  "Don't call yourself a junior dev 🙅🏿",
  'One job please! 💰',
  // "community goal met 🎉",
  'Bob gets mentioned by Dies or slides',
  'Dylan spits hot fire 🔥🔥',
  //'The Bachelor 🌹',
  //'Dad Joke 📣',
  'Dies uses the phrase "wiggity-wack"',
  "Dorito's 🍕",
  'Machi/Simba borks in the background 🐕',
  'Dies transforms into Little Dies',
  "It looks like we're going to run a little late",
  //'Dies forgets and then remembers that bingo exists',
  'You messed up',
  // "Dies polls the crowd",
  //"spend Jeff Bezos' money! 💸",
  'Not that kind of stream, folx!',
  'Join us for office hours! 🕘',
  'We reach a level 5 hype train! 🚂',
  'Party Mode Activated! 🎊',
  // "Doggo Cam activated 🐶",
  "You're a full stack dev now! 🏆",
  'Someone redeems soundboard alert 🔊',
  'First tryyy! 👍🏿',
  "We don't get got, we go get 😎",
  'Dies gets spicy 🌶️',
  "We're going to finish early today",
  'You remembered to check in on Twitter',
  "You're signed up for Dies's newsletter",
  "You're taking care of yourself 🛀🏾",
  'We get raided by another streamer',
  "You're keeping up with your Anki deck 🧠"
];
