/**
 * @typedef {Array} phraseBank
 * @description This is where we store all of our phrases that we want to use for bingo tiles.
 */

const phraseBank = [
  "43",
  '"What does that MEAN? ✨✨"',
  "OVERTIME ⏲️",
  '"Get out your phones! 📱"',
  "Follow @sfados 📷",
  "Renter's Insurance! 💰💰",
  "Free Stuff! 🎉",
  "Hot fire 🔥🔥",
  '"The GOOD group 👼🏽"',
  "Dad Joke 🤣🤣",
  '"Wiggity-wack" 🤪',
  "Dorito's 🍕",
  'Melon 🐕',
  '"Ask for what?? HELP!" 🆘',
  '"Emotions are natural"',
  "Crowd-poll! 📣",
  '"Saving you money! 💸"',
  "ESA's & Service Animals 🐶",
  "You're a lumberjack now! ",
  "The 80's 😎",
  '🌶️🌶️🌶️',
  'Illegal surge protectors',
  'You asked for HELP 🆘',
  'FERPA!',
  '"The OTHER group 😈"',
  "Questions ❔❔",
  "Self-care 🛀🏾",
  'Heckler Alert! ⚠️',
  'Dean of Parents',
  'Emergency Aid fund 💰',
  '"Not a Judgment-Free Zone"',
  '"Ask me 4 questions"',
  'Counselor + Principal = Dean 🎓',
  'Communication 💬',
  'Student Food Pantry 🥫🥫',
  "Margaritas!",
  '"We could be friends!"',
  "CONDUCT",
  "Meningitis vaccination 💉",
  "You signed up for renter's insurance 👑👑",
  "You visited your college 🏆",
  "You signed FERPA ⚙️",
  "You joined Parent Connection 🧼",
];
